const players = [
    {
      id: 1,
      name: "Lionel Messi",
      age: 34,
      nationality: "Argentina",
      team: "Barcelone",
      jerseyNumber: 10,
      position: "Forward",
      rating: 99,
      image: "https://www.aljazeera.com/wp-content/uploads/2022/12/SSS10784_1.jpg?resize=1800%2C1800",
    },
    {
      id: 2,
      name: "Mohamed Salah",
      age: 30,
      nationality: "Egypt",
      team: "Liverpool",
      jerseyNumber: 11,
      position: "Forward",
      rating: 90,
      image: "https://media.letelegramme.fr/api/v1/images/view/6382da0f639cc44fe96dbfd5/web_golden_xl/6382da0f639cc44fe96dbfd5.1",
    },
    {
      id: 3,
      name: "Neymar Jr.",
      age: 29,
      nationality: "Brazil",
      team: "Paris Saint-Germain",
      jerseyNumber: 10,
      position: "Forward",
      rating: 91,
      image: "https://i.pinimg.com/736x/16/73/6f/16736f252e8308cab2c3fccdd18f510c.jpg",
    },
    {
      id: 4,
      name: "Kevin De Bruyne",
      age: 30,
      nationality: "Belgium",
      team: "Manchester City",
      jerseyNumber: 17,
      position: "Midfielder",
      rating: 89,
      image: "https://www.sportsnet.ca/wp-content/uploads/2022/04/de_bruyne_kevin1280-640x360.jpg",
    },
    {
        id: 5,
        name: "Karim Benzema",
        age: 35,
        nationality: "France",
        team: "Real Madrid",
        jerseyNumber: 9,
        position: "Forward",
        rating: 93,
        image: "https://pbs.twimg.com/media/FInIP7wWQAAEE0a.jpg",
    },
    {
        id: 6,
        name: "Sergio Ramos",
        age: 37,
        nationality: "Espagne",
        team: "Real Madrid",
        jerseyNumber: 4,
        position: "Defender",
        rating: 88,
        image: "https://i2-prod.mirror.co.uk/incoming/article12606078.ece/ALTERNATES/s1200c/Sergio-Ramos-laughing-and-joking-after-injuring-Mo-Salah.jpg",
    }
  ];
  
  export default players;